In [16]:
import pandas as pd
import os

# Leer el archivo "obesidad.csv"
obesidad = pd.read_csv(os.path.join("obesidad.csv"))

# Ordenar el DataFrame "obesidad" por la columna "Name" en orden alfabético
obesidad = obesidad.sort_values(by='Name')

# Reiniciar los índices después de ordenar
obesidad.reset_index(drop=True, inplace=True)

# Eliminar la columna "Pos" y cambiar el nombre de "Name" a "Country"
obesidad = obesidad.drop(columns=['Pos'])
obesidad = obesidad.rename(columns={'Name': 'Country'})

# Cambiar el nombre de la columna "Value" a "Obesity_adult_prevalence_rate"
obesidad = obesidad.rename(columns={'Value': 'Obesity_adult_prevalence_rate'})

# Cambiar el texto en la columna "Country" de minúsculas a mayúsculas
obesidad['Country'] = obesidad['Country'].str.upper()

In [17]:
obesidad

            Country  Obesity_adult_prevalence_rate
0       AFGHANISTAN                            2.2
1           ALBANIA                           21.3
2           ALGERIA                           16.0
3    AMERICAN SAMOA                           74.6
4           ANDORRA                           25.2
..              ...                            ...
186       VENEZUELA                           30.3
187         VIETNAM                            1.7
188           YEMEN                           14.5
189          ZAMBIA                            3.6
190        ZIMBABWE                            7.0

[191 rows x 2 columns]